---
abstract: "Access to USF's online directory"
author:
  - 'Douglas Christopher Wilson <doug@somethingdoug.com>'
build_requires:
  Test::Exception: 0.03
  Test::More: 0.94
  Test::Override::UserAgent: 0
  Test::Requires: 0.02
  URI::QueryParam: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-USF-Directory
no_index:
  directory:
    - inc
    - t
    - xt
provides:
  WWW::USF::Directory:
    file: lib/WWW/USF/Directory.pm
    version: 0.003
  WWW::USF::Directory::Entry:
    file: lib/WWW/USF/Directory/Entry.pm
    version: 0.003
  WWW::USF::Directory::Entry::Affiliation:
    file: lib/WWW/USF/Directory/Entry/Affiliation.pm
    version: 0.003
  WWW::USF::Directory::Exception:
    file: lib/WWW/USF/Directory/Exception.pm
    version: 0.003
  WWW::USF::Directory::Exception::MethodArguments:
    file: lib/WWW/USF/Directory/Exception/MethodArguments.pm
    version: 0.003
  WWW::USF::Directory::Exception::TooManyResults:
    file: lib/WWW/USF/Directory/Exception/TooManyResults.pm
    version: 0.003
  WWW::USF::Directory::Exception::UnknownResponse:
    file: lib/WWW/USF/Directory/Exception/UnknownResponse.pm
    version: 0.003
requires:
  Carp: 0
  Const::Fast: 0.004
  English: 0
  HTML::HTML5::Parser: 0.101
  List::MoreUtils: 0.07
  Moose: 0.89
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.08
  MooseX::Types::Common: 0
  MooseX::Types::Email: 0
  MooseX::Types::Moose: 0
  MooseX::Types::URI: 0
  Net::SAJAX: 0.102
  namespace::clean: 0.04
  perl: 5.008001
resources:
  homepage: http://github.com/dougwilson/perl5-www-usf-directory/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/dougwilson/perl5-www-usf-directory.git
version: 0.003
